# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['MONITORING-SYSTEM_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['MONITORING-SYSTEM_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['MONITORING-SYSTEM_DATABASE'] %>
  username: <%= ENV['MONITORING-SYSTEM_DATABASE_USERNAME'] %>
  password: <%= ENV['MONITORING-SYSTEM_DATABASE_PASSWORD'] %>